### PR TITLE
chore: ignore dartdoc generated api files

### PR DESCRIPTION
**Pull request by chalin**
Followup to #26, #40. Third time's a charm they say ;).

cc @kevmoo @kwalrath

### CODE REVIEW

**Comment by kevmoo** [comment]
Waiting for the CLA bot to fire...

**Comment by chalin** [comment]
CLA bot must have taken a day off. I've resubmitted and now it's happy.

**Comment by kwalrath** [comment]
If nobody adds this, I'll add it myself. It was a bit shocking, working on the cheatsheet doc files, to see that my branch had 4,574 changes!

**Comment by kevmoo** [comment]
@kwalrath LGTM - make it happen!

**Comment by kwalrath** [comment]
I'm including this in my internal commit of #56.

**Pull request closed without merging**
