### PR TITLE
Add an AUTHORS file

### PR DESCRIPTION
**Pull request by kevmoo**
Closes https://github.com/dart-lang/angular2/issues/91

### CODE REVIEW

**Comment by adaojunior** [comment]
@kevmoo  It is currently saying `to the Flutter project`.

**Comment by kevmoo** [comment]
Modified output of `git log --format='%aN <%aE>' | sort -f | uniq | grep -v google`

@zoechigist @kulshekhar @ntaoo Would you like your full name used? Please advise

**Comment by kevmoo** [comment]
> It is currently saying to the Flutter project.

It's like you know where I copied it from... 😉

**Comment by kulshekhar** [comment]
@kevmoo  I'm fine with either. In case there's a need to use the full name, it's Kulshekhar Kabra

**Comment by ntaoo** [comment]
@kevmoo It's Naoto Higuchi <ntaoo.g@gmail.com>

**Comment by zoechi** [comment]
@kevmoo yup
Günter Zöchbauer or Guenter Zoechbauer
guenter@gzoechbauer.com

**Comment by kevmoo** [comment]
Thanks @zoechigist @kulshekhar @ntaoo – Ya'll might wanna tweak your .gitconfig settings accordingly in the future 😄

**Pull request closed without merging**
