### PR TITLE
Improve how ngFor processes changes in a list

### LINKED ISSUE #102: Deleting an item from a list modifies subsequent DOM siblings
When an item is deleted from a list and if the list is used in a template via `ngFor`, all the subsequent DOM siblings of the HTML element corresponding to the deleted item are being modified.

Here's an illustration of what's happening (notice the elements being modified in dev tools) : 

What is expected: 

Code used:

Component: https://gist.github.com/kulshekhar/e1d7cfb5fc04b4ed6246cedfa3a05dc6
Template: https://gist.github.com/kulshekhar/97b7ae7e7f696a27ff1b3fe25574773e

The rest of the setup was as described in the [QuickStart guide](https://angular.io/docs/dart/latest/quickstart.html)

Angular version used: 2.0.0-beta.22

### PR DESCRIPTION
**Pull request by kulshekhar**
This should fix #102

### CODE REVIEW

**Comment by kulshekhar** [comment]
One test in the content shell is failing. Closing this PR while I fix it.

**Comment by kulshekhar** [comment]
Fixed the bug

**Comment by kulshekhar** [comment]
This isn't working as expected :(

The last fix (for incorrect indices) has caused the original issue to resurface. I'm going to take a closer look at this and start by writing some tests.

Should I close this PR permanently and open a new one once I've got this working?

**Comment by ferhatb** [comment]
Thank you for PR. In queue for next sync.

**Pull request closed without merging**
