### PR TITLE
Cheatsheet updates: SwitchCase, EventEmitter

### PR DESCRIPTION
**Pull request by chalin**
- Dropped `EventEmitter`
- `ngSwitchWhen` --> `ngSwitchCase`

cc @kwalrath

### CODE REVIEW

**Comment by chalin** [comment]
Yes. Here:
screen shot 2017-04-25 at 1 57 38 pm

And here:
screen shot 2017-04-25 at 1 57 26 pm

**Comment by kwalrath** [comment]
Looks great. @kevmoo can you incorporate this?

**Comment by chalin** [comment]
@kevmoo, @ferhatb - after some discussion, @kwalrath and I agreed to move the cheatsheet doc sources to site-webdev ... so that you won't need to be bothered anymore with updates like these in the future.

**Comment by chalin** [comment]
See #360

**Comment by zoechi** [comment]
shouldn't `sync: true` be suggested for the `StreamController`?

**Comment by matanlurey** [comment]
Synchronous stream controllers are usually only meant to adapt already
asynchronous APIs that aren't Stream based (similar to Completer is to
Future).

**Comment by zoechi** [comment]
I haven't checked for a long time. I just thought to remember that this was made the default in EventEmitter long ago because of timing issues.
If this isn't the case please ignore my comments.

**Pull request closed without merging**
