### PR TITLE
API docs: replace @example with @source + inlined code

### PR DESCRIPTION
**Pull request by chalin**
Here is an example from the [staged site](https://angulardart-org-dev.firebaseapp.com/angular): [NgStyle](https://angulardart-org-dev.firebaseapp.com/angular/api/angular2.common/NgStyle-class).

Contributes to https://github.com/dart-lang/site-webdev/issues/338

Note that `@example` directives that referred to `.ts` code have been written as `{@disabled-source ...}` entries. These will be converted to proper `@source` entries in a follow-up commit.

cc @kwalrath @matanlurey @thso @kevmoo

### CODE REVIEW

**Comment by kevmoo** [comment]
@chalin to be clear: do you want this merged or no?

Please update the title if this is just  work-in-progress (WIP)

**Comment by chalin** [comment]
@kevmoo: This is ready for review and merge, though I now see that Travis is reporting errors, so I'll look into that. But I recall Kathy telling me that there were some issues with Travis?

**Comment by ferhatb** [comment]
i'll attempt a merge now

**Comment by chalin** [comment]
I see that master has the same errors as this PR, so as I mentioned before, it is ready for review and merge.

**Comment by kwalrath** [comment]
Should we be using labels like "State: merged internally" (or maybe a new one, "State: merged" for stuff that's already visible externally)?

**Comment by kevmoo** [comment]
What do you mean "visible"?

I just use those for tracking as-yet synced pull requests.

If they exist on closed PR, I'm not concerned...

**Comment by kwalrath** [comment]
Somebody looking at these PRs might think that they weren't merged. But they were. So I thought it might be nice to have a label saying what the merge state is.

We already have (but didn't use for this PR) a label (State: merged internally) for stuff that's merged in our internal repo but perhaps not yet merged to the GitHub repo. I was also wondering whether we wanted a label for stuff that had made it to the external repo, although I suspect we might forget to update it.

**Comment by kevmoo** [comment]
> ferhatb closed this in 99a8816 6 days ago

This is the key thing, I think. We could always go through and clean-up the labels and add the "really merged to github" -- if one were to think that was important :smile:

**Pull request closed without merging**
