### PR TITLE
Format comments based on the dart style guide

### PR DESCRIPTION
**Pull request by adaojunior**
Hi, I tried to follow the dart style guide, for library descriptions I used `//` instead of `///` because that's what I've seen in other dart-lang packages. I also tried to port the TS examples to dart as well. This PR only changes files on `lib/src/common`. Hopefully this will be helpful.

cc @kwalrath

### CODE REVIEW

**Comment by adaojunior** [comment]
Oh btw, I removed some of the `/** @internal */` comments, seems like they're only needed on TS, but let me know if I should put them back.

**Comment by kevmoo** [comment]
Please rebase on the latest `master` – we now have travis enabled.

Also, please use triple-tick style code comments with a "dart" header.

Thanks!

**Comment by kevmoo** [comment]
@adaojunior did you rebase on the latest master? This seems like a lot of commits. 😄

**Comment by adaojunior** [comment]
@kevmoo lol Sorry I mess up, I'm not quite sure how to rebase this, this is what I did:

```
git remote add upstream https://github.com/dart-lang/angular2.git
git fetch upstream
git rebase upstream/master
```

**Comment by kevmoo** [comment]
Here you go - https://github.com/dart-lang/angular2/tree/adaojunior_pr_29

I had to skip one commit – but your commit came through fine

**Comment by adaojunior** [comment]
@kevmoo sorry, what should I do now ?

**Comment by kevmoo** [comment]
```
git checkout [local branch with this change]
git fetch --all
git reset --hard upstream/adaojunior_pr_29
```

That should make your local branch mirror the branch I created for you perfectly.

If so, then.

```
git push [origin or whatever your fork is called] --force
```

**Comment by adaojunior** [comment]
thank you :D

**Comment by kevmoo** [comment]
@adaojunior did you see my comment earlier

> Also, please use triple-tick style code comments with a "dart" header.

**Comment by adaojunior** [comment]
@kevmoo Yes, I'll fix that soon.

**Comment by adaojunior** [comment]
@kevmoo I updated the dart code to use triple-tick style code comments but I left html code as it was before.

**Comment by kevmoo** [comment]
Let's do the html comments in another pull request – it'll be easier to merge things if we take small steps.

**Comment by kevmoo** [comment]
Thank you so much, @adaojunior – this will hopefully be in our next big commit

**Comment by adaojunior** [comment]
@kevmoo you're welcome, let me know if I should keep these changes, I'm not sure if it is a priority for the dart team right now, I want to sent some PR mostly making the code more friendly and following the dart style guide, I started with comments but I plan to remove some of the `this.` as well since it is not really needed.

**Pull request closed without merging**
