### PR TITLE
Update docs to use tripple slash notation

### PR DESCRIPTION
**Pull request by b-strauss**

### CODE REVIEW

**Comment by b-strauss** [comment]
Fixes #88

**Comment by kevmoo** [comment]
@b-strauss We've done a BUNCH of refactoring internally, so this doesn't merge cleanly.

When we land the next release (should be soon) please rebase and we'll make sure to pull this in ASAP

Thanks for your patience!

**Comment by b-strauss** [comment]
@kevmoo Thanks for the info. Are there plans to eventually shift the internal development at google completely to github?

**Comment by kevmoo** [comment]
> Thanks for the info! Are there plans to eventually shift the internal development at google completely to github?

Likely not. There is a *mountain* of awesome sauce internally that ensures this package stays super high quality.

What we *do* want to do: make the split between what's internal and external less visible by syncing much more often. That's a ways out, but it's on our radar.

**Comment by b-strauss** [comment]
cc @kevmoo

**Comment by b-strauss** [comment]
Thanks. Do I have to fix the cla message, or is this done?

**Comment by kevmoo** [comment]
See https://github.com/kevmoo/angular2/tree/kevmoo_pr_84

Make sure the commit message for that one commit is clear on what you're doing.

**Comment by b-strauss** [comment]
Snap, I messed up something. Is there a way to reopen this?

**Comment by kevmoo** [comment]
Can't – you deleted the branch associated. 😕

**Comment by kevmoo** [comment]
No pain in creating another CL.

**Comment by b-strauss** [comment]
I still had it locally and pushed it again. :)

Ok I will first rebase properly.

**Pull request closed without merging**
