### PR TITLE
Use forEach less, added some finals

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by adaojunior** [comment]
Hi, I'm curious, why are you switching forEach to for ?

**Comment by kevmoo** [comment]
> Hi, I'm curious, why are you switching forEach to for ?

`for...each` is easier to optimize. There is no closure. The compiler doesn't have to worry about `.forEach` being overridden in a subclass.

**Comment by kwalrath** [comment]
Should we mention this in the docs?

**Comment by matanlurey** [comment]
Maybe for the contributing guide, but this isn't a requirement users.

**Pull request closed without merging**
