### PR TITLE
docs: remove cheatsheet `*.md` files

### LINKED ISSUE #360: docs: move cheatsheet *.md files to site-webdev
As agreed to with @kwalrath.

https://github.com/dart-lang/site-webdev/issues/571 is the corresponding webdev-side issue.

### PR DESCRIPTION
**Pull request by chalin**
The files are being moved to https://github.com/dart-lang/site-webdev.
Contributes to https://github.com/dart-lang/site-webdev/issues/571
Fixes #360

cc @kwalrath

### CODE REVIEW

**Comment by kwalrath** [comment]
Is there a corresponding PR for site-webdev?

**Comment by chalin** [comment]
Yes, https://github.com/dart-lang/site-webdev/pull/618. (I had started looking into having static Jade/markdown files for the cheatsheet, rather than depend on the api-builder scripts, but in the end decided to do that later.)

**Comment by matanlurey** [comment]
Can you rebase? Happy to land tomorrow.

**Comment by chalin** [comment]
Rebased. Thanks.

**Pull request closed without merging**
